services:
  - type: web
    name: backend_test
    plan: free
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/helloapp-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
